name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    # 移除矩阵策略，只使用单个Python版本
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 安装allure命令行工具
        sudo apt-get update
        sudo apt-get install -y default-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz
        sudo tar -zxvf allure-2.23.1.tgz -C /opt/
        sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

    - name: Run tests and generate report
      run: |
        python run.py
      env:
        # 在CI环境中禁用邮件发送功能
        # DISABLE_EMAIL: true
        # 标记为GitHub Actions环境
        GITHUB_ACTIONS: true

    - name: Check test results
      run: |
        echo "检查测试结果文件..."
        ls -la reports/
        echo "检查临时测试结果..."
        if [ -d "reports/temps" ]; then
          echo "临时测试结果文件数量: $(ls -1 reports/temps | wc -l)"
          ls -la reports/temps/
        else
          echo "未找到临时测试结果目录"
        fi
        echo "检查生成的Allure报告..."
        if [ -d "reports/allures" ]; then
          echo "Allure报告文件数量: $(ls -1 reports/allures | wc -l)"
          ls -la reports/allures/
        else
          echo "未找到Allure报告目录"
        fi

    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: report
        path: reports/allures/

    - name: Run linting
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics